# reload config
unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# prefix
set -g prefix C-s

# pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# pane resizing
bind -n M-h resize-pane -L 5
bind -n M-j resize-pane -D 5
bind -n M-k resize-pane -U 5
bind -n M-l resize-pane -R 5

set-option -g automatic-rename off

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

# status bar
set -g status-position bottom
set -g status-left-length 100
set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_session}"
set -g status-left ""

# catppuccin
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_number_color "#d3c6aa"
set -g @catppuccin_window_number_color "#{@thm_surface_0}"

run '~/.tmux/plugins/tpm/tpm'
